### PR TITLE
babyArray is a simpler version of SimpleArraySum that I'll use to learn about bufio

### PR DESCRIPTION
**Pull request by gweitkemper**
… in main

### CODE REVIEW

**Comment by gweitkemper** [comment]
@grembinni check out line 35 in babyArray the i variable is being dumb.

**Comment by grembinni** [comment]
What is the goal of this file? It is just doing a ioUtils and arraySome functions. Do we need/want to size arrays before populating?

**Comment by gweitkemper** [comment]
> What is the goal of this file? It is just doing a ioUtils and arraySome functions. Do we need/want to size arrays before populating?

This is really just a way of teaching myself a bit more about how the ioUtils work and the array stuff.  I don't know that we'll need it long term but bufio is weird to me and this bridges the gap.  As for the asking for the length, that's part of the problem from hacker rank

**Comment by gweitkemper** [comment]
> not wild about the readability of nested functions - I'd recommend making this one line, 3 lines

Agreed, updated.... I do think that 
reader := initReader()
array := readLineAsInts(reader, " ")

might be cleaner as 
array := readLineAsInts(initReader(), " ")

maybe I just hate initReader taking up two lines all the time but it's not the end of the world

**Comment by grembinni** [comment]
its all subjective, I think nesting the initReader would be fine - as long as you arent reusing the reader again

Im down for one nested method - not 4 : P

**Review by grembinni — APPROVED** [review]

**Pull request merged**
